name: e_learning
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_spinkit: ^4.1.2+1
  google_fonts: ^1.1.0
  shared_preferences: ^0.5.12
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.1+1
  google_sign_in: ^4.5.4
  cloud_firestore: ^0.14.1+2
  material_design_icons_flutter: ^4.0.5655
  url_launcher: ^5.7.2
  webview_flutter: ^1.0.0
  razorpay_flutter: ^1.2.2
  toast: ^0.1.5
  http:
  permission_handler: ^5.0.1+1
  flutter_pdfview: ^1.0.0+10
  path_provider: ^1.6.5
  flutter_windowmanager: ^0.0.1+1
  numeric_keyboard: ^1.0.0
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  provider: ^4.0.4
  firebase_messaging: ^7.0.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.8.1
  mobx_codegen: ^1.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/logo.png
    - assets/images/student.png
    - assets/images/admin.png
    - assets/images/header.png
    - assets/images/liveclass.jpg
    - assets/images/doubt.jpg
    - assets/images/assesment.png
    - assets/images/proteacher.png
    - assets/images/topics.jpg
    - assets/images/certificate.png
    - assets/images/feedback.png
    - assets/images/improvement.png
    - assets/icons/home.png
    - assets/images/price1.jpg
    - assets/images/maths.png
    - assets/images/wordcloud.png
    - assets/images/Presentation1.jpg
    - assets/images/holding-phone.png
    - assets/images/sign.png
    - assets/logo/google.jpg
    - assets/logo/phone.png
    - assets/images/price2.jpg
    - assets/images/price3.jpg
    - assets/images/price4.jpg
    - assets/images/sevenp2.jpg
    - assets/images/fivep1.jpg
    - assets/images/fivep2.jpg
    - assets/logo/whatsapp.png
    - assets/logo/facebook.png
    - assets/images/about.jpg
    - assets/images/nine.jpg
    - assets/images/seven.jpg
    - assets/images/T1.jpg
    - assets/images/T2.jpg
    - assets/images/T3.jpg
    - assets/images/whiteboard.png
    - assets/images/weekend.png
    - assets/images/basica.jpg
    - assets/images/intermediatea.jpg
    - assets/images/advancea.jpg
    - assets/images/experta.jpg
    - assets/images/basicb.jpg
    - assets/images/advanceb.jpg
    - assets/images/basicc.jpg
    - assets/images/advancec.jpg
    - assets/logo/lomgo.png
    - assets/images/newhome.jpg
    - assets/images/onestep.jpg
    - assets/images/slider1.jpg
    - assets/images/slider2.jpg
    - assets/images/slider3.jpg

  



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
fonts:
  - family: OpenSans
    fonts:
      - asset: fonts/SecularOne-Regular.ttf
  - family: Futura
    fonts:
      - asset: fonts/Peddana-Regular.ttf  
  - family: Anton
    fonts:
      - asset: fonts/Anton-Regular.ttf    
  - family: Dance 
    fonts:
      - asset: fonts/DancingScript-VariableFont_wght.ttf
  - family: Futuralight
    fonts:
      - asset: fonts/Futura Light.ttf    

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
